# Generated by Django 4.1 on 2022-08-10 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_alter_dailyreportsmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportsmodel',
            name='author',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
